version: '3'
services:
  python3.7:
    container_name: python3.7-tests
    working_dir: /opt/api
    image: python:3.7
    volumes:
      - './:/opt/api'

  python3.8:
    container_name: python3.8-tests
    working_dir: /opt/api
    tty: true
    image: python:3.8
    volumes:
      - './:/opt/api'

  python3.9:
    container_name: python3.9-tests
    working_dir: /opt/api
    image: python:3.9
    volumes:
      - './:/opt/api'
