name: API - CI

on:
  push:
    paths:
      - api/**
    branches:
      - master
      - "*"
      - "*/*"
    tags:
      "*.*.*"
  pull_request:
    branches:
      - master
      - "*/*"

jobs:
  python38:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Spin up docker container
        run: docker-compose -f api/docker-compose.ci.yml up -d python3.8

      - name: install requirements-dev.txt
        run: docker-compose -f api/docker-compose.ci.yml exec -T python3.8 pip install -r requirements-dev.txt

      - name: install linux-commands-mocking to mock commands - step 1
        run: docker-compose -f api/docker-compose.ci.yml exec -T python3.8 wget -O /tmp/remote_install.sh https://raw.githubusercontent.com/ibra-akv/linux-commands-mocking/master/remote_install.sh

      - name: install linux-commands-mocking to mock commands - step 2
        run: docker-compose -f api/docker-compose.ci.yml exec -T python3.8 chmod +x /tmp/remote_install.sh

      - name: install linux-commands-mocking to mock commands - step 3
        run: docker-compose -f api/docker-compose.ci.yml exec -T python3.8 sh /tmp/remote_install.sh

      - name: copy cli_mock_map.json
        run: docker-compose -f api/docker-compose.ci.yml exec -T python3.8 cp /opt/api/tests/raw/cli/cli_mock_map.json /usr/local/climate/

      - name: create symlinks
        run: docker-compose -f api/docker-compose.ci.yml exec -T python3.8 python3 /usr/local/climate/symlinker.py --mock-map-file=/usr/local/climate/cli_mock_map.json --mock-dir=/usr/local/climate

      - name: create linuxtower user
        run: docker-compose -f api/docker-compose.ci.yml exec -T python3.8 bash -c "useradd -ms /bin/bash linuxtower"

      - name: add password to linuxtower user
        run: docker-compose -f api/docker-compose.ci.yml exec -T python3.8 bash -c "echo 'linuxtower:linuxtower' | chpasswd"

      - name: run tests
        run: docker-compose -f api/docker-compose.ci.yml exec -T python3.8 pytest tests -p no:warnings --cov=./ --cov-report=xml

      - name: CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: ./api/coverage.xml